# Generated by Django 5.2.17 on 2026-08-25 05:53

import careers.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('employment_type', models.CharField(max_length=100)),
                ('workplace_type', models.CharField(max_length=100)),
                ('experience_required', models.CharField(max_length=255)),
                ('education_required', models.CharField(max_length=255)),
                ('salary_display', models.CharField(default='As per Experience + Attractive Performance-Based Incentives', max_length=255)),
                ('responsibilities', models.JSONField(blank=True, default=list)),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('preferred_skills', models.JSONField(blank=True, default=list)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Closed', 'Closed')], default='Draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('current_city', models.CharField(max_length=255)),
                ('current_address', models.TextField(blank=True, null=True)),
                ('highest_education', models.CharField(max_length=255)),
                ('current_company', models.CharField(blank=True, max_length=255, null=True)),
                ('current_job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('total_experience', models.CharField(max_length=100)),
                ('sales_marketing_experience', models.CharField(blank=True, max_length=100, null=True)),
                ('expected_salary', models.CharField(max_length=100)),
                ('notice_period', models.CharField(max_length=100)),
                ('why_join', models.TextField(blank=True, null=True)),
                ('has_two_wheeler', models.BooleanField(default=False)),
                ('comfortable_with_field_marketing', models.BooleanField(default=False)),
                ('comfortable_with_business_visits', models.BooleanField(default=False)),
                ('resume', models.FileField(upload_to=careers.models.resume_upload_path, validators=[careers.models.validate_resume_extension])),
                ('consent_accepted', models.BooleanField(default=False)),
                ('application_status', models.CharField(choices=[('New', 'New'), ('Under Review', 'Under Review'), ('Shortlisted', 'Shortlisted'), ('Interview Scheduled', 'Interview Scheduled'), ('Selected', 'Selected'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn')], default='New', max_length=30)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='careers.job')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
    ]
