# Generated by Django 5.2.17 on 2026-08-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='department',
            field=models.CharField(default='Sales & Marketing', max_length=255),
        ),
    ]
