# Generated by Django 5.2.17 on 2026-08-25 06:44

import careers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_job_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(upload_to=careers.models.resume_upload_path, validators=[careers.models.validate_resume_extension, careers.models.validate_resume_size]),
        ),
    ]
