# Generated by Django 5.2.17 on 2026-08-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Nexus Nutraceuticals', max_length=255)),
                ('website_name', models.CharField(default='Nexus Nutraceuticals', max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp_number', models.CharField(default='6357002100', help_text='Number only, without +91 or spaces', max_length=20)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('marketed_by_name', models.CharField(default='Nexus Nutraceuticals', max_length=255)),
                ('marketed_by_address', models.CharField(blank=True, max_length=500, null=True)),
                ('marketed_by_city', models.CharField(default='Ahmedabad', max_length=100)),
                ('marketed_by_state', models.CharField(default='Gujarat', max_length=100)),
                ('marketed_by_pin', models.CharField(default='382418', max_length=20)),
                ('marketed_by_country', models.CharField(default='India', max_length=100)),
                ('manufactured_by_name', models.CharField(default='Genix Nutraceuticals LLP', max_length=255)),
                ('manufactured_by_address', models.CharField(blank=True, max_length=500, null=True)),
                ('manufactured_by_city', models.CharField(blank=True, max_length=100, null=True)),
                ('manufactured_by_state', models.CharField(default='Gujarat', max_length=100)),
                ('manufactured_by_pin', models.CharField(blank=True, max_length=20, null=True)),
                ('manufactured_by_country', models.CharField(default='India', max_length=100)),
                ('fssai_license', models.CharField(blank=True, max_length=50, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Website Settings',
                'verbose_name_plural': 'Website Settings',
            },
        ),
    ]
