# Generated by Django 5.2.17 on 2026-08-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='cgst_rate',
            field=models.DecimalField(decimal_places=2, default=2.5, help_text='CGST percentage (e.g., 2.50)', max_digits=5),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Total GST percentage (e.g., 5.00)', max_digits=5),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='sgst_rate',
            field=models.DecimalField(decimal_places=2, default=2.5, help_text='SGST percentage (e.g., 2.50)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Enter number with country code, no +, no spaces (e.g., 916357002100)', max_length=20, null=True),
        ),
    ]
